# -*- coding: utf-8 -*-
"""Copy of Aula007-SVM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mETsV21augdIrnHaRRkDpYRQ2lwrxly
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X, y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

svm = Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC(kernel="rbf", C=1, gamma="scale"))
])

knn = Pipeline([
    ("scaler", StandardScaler()),
    ("model", KNeighborsClassifier(n_neighbors=5))
])

svm.fit(X_train, y_train)
knn.fit(X_train, y_train)

pred_svm = svm.predict(X_test)
pred_knn = knn.predict(X_test)

print("Acurácia SVM:", accuracy_score(y_test, pred_svm))
print("Acurácia KNN:", accuracy_score(y_test, pred_knn))

import numpy as np
import matplotlib.pyplot as plt
import cv2

from PIL import Image
from google.colab import files

from tensorflow.keras.datasets import mnist

from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# Carregar MNIST: imagens 28x28 de dígitos escritos à mão
(X_train_img, y_train), (X_test_img, y_test) = mnist.load_data()

# Para não ficar muito lento no Colab, usamos uma parte da base
X_train_img = X_train_img[:12000]
y_train = y_train[:12000]

X_test_img = X_test_img[:2000]
y_test = y_test[:2000]

# Normalizar para 0 a 1
X_train = X_train_img.reshape(len(X_train_img), -1) / 255.0
X_test = X_test_img.reshape(len(X_test_img), -1) / 255.0

print("Treino:", X_train.shape)
print("Teste:", X_test.shape)

modelo_svm = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="rbf", C=10, gamma="scale"))
])

modelo_svm.fit(X_train, y_train)

y_pred = modelo_svm.predict(X_test)

print("Acurácia:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.metrics import ConfusionMatrixDisplay
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

# Re-load the MNIST test data to get the correct y_test,
# ensuring it hasn't been overwritten by other datasets.
_, (X_test_img_temp, y_test_mnist_corrected) = mnist.load_data()
y_test_mnist_corrected = y_test_mnist_corrected[:2000] # Truncate to match previous processing

ConfusionMatrixDisplay.from_predictions(y_test_mnist_corrected, y_pred)
plt.title("Matriz de Confusão - SVM")
plt.show()

def preparar_digito_mnist(imagem_np):
    img = imagem_np.astype(np.uint8)

    # Suaviza um pouco
    img_blur = cv2.GaussianBlur(img, (3, 3), 0)

    # Como o dígito é preto no fundo branco,
    # usamos THRESH_BINARY_INV para transformar:
    # fundo -> preto
    # número -> branco
    _, thresh = cv2.threshold(
        img_blur,
        0,
        255,
        cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )

    # Encontrar pixels do dígito
    coords = cv2.findNonZero(thresh)

    if coords is None:
        raise ValueError("Nenhum dígito encontrado.")

    x, y, w, h = cv2.boundingRect(coords)

    # Recorta já a imagem binarizada, sem o fundo cinza
    digito = thresh[y:y+h, x:x+w]

    # Mantém proporção e redimensiona para caber em 20x20
    altura, largura = digito.shape

    if altura > largura:
        nova_altura = 20
        nova_largura = max(1, int(largura * 20 / altura))
    else:
        nova_largura = 20
        nova_altura = max(1, int(altura * 20 / largura))

    digito_redim = cv2.resize(
        digito,
        (nova_largura, nova_altura),
        interpolation=cv2.INTER_AREA
    )

    # Cria imagem 28x28 preta
    digito_28 = np.zeros((28, 28), dtype=np.uint8)

    # Centraliza
    x_offset = (28 - nova_largura) // 2
    y_offset = (28 - nova_altura) // 2

    digito_28[
        y_offset:y_offset+nova_altura,
        x_offset:x_offset+nova_largura
    ] = digito_redim

    # Normaliza igual ao MNIST
    vetor = digito_28.reshape(1, -1) / 255.0

    return vetor, digito_28

uploaded = files.upload()

nome_arquivo = list(uploaded.keys())[0]

imagem = Image.open(nome_arquivo).convert("L")
imagem_np = np.array(imagem)

vetor, digito_processado = preparar_digito_mnist(imagem_np)

predicao = modelo_svm.predict(vetor)[0]

plt.figure(figsize=(7, 3))

plt.subplot(1, 2, 1)
plt.imshow(imagem_np, cmap="gray")
plt.title("Original")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(digito_processado, cmap="gray")
plt.title("28x28 usado pelo SVM")
plt.axis("off")

plt.show()

print("Número reconhecido pelo SVM:", predicao)

scores = modelo_svm.decision_function(vetor)[0]

for numero, score in enumerate(scores):
    print(f"{numero}: {score:.4f}")

arquivos = [
    "0.png", "1.png", "2.png", "3.png", "4.png",
    "5.png", "6.png", "7.png", "8.png", "9.png"
]

plt.figure(figsize=(14, 18))

for i, nome_arquivo in enumerate(arquivos):
    imagem = Image.open(nome_arquivo).convert("L")
    imagem_np = np.array(imagem)

    vetor, digito_processado = preparar_digito_mnist(imagem_np)
    predicao = modelo_svm.predict(vetor)[0]

    real = int(nome_arquivo[0])

    # Pega uma imagem de exemplo do MNIST com a classe predita
    indice_modelo = np.where(y_train == predicao)[0][0]
    imagem_modelo = X_train_img[indice_modelo]

    # Coluna 1: sua letra processada
    plt.subplot(10, 2, i * 2 + 1)
    plt.imshow(digito_processado, cmap="gray")
    plt.title(f"Sua letra | Real: {real} | Pred: {predicao}")
    plt.axis("off")

    # Coluna 2: exemplo do modelo/MNIST
    plt.subplot(10, 2, i * 2 + 2)
    plt.imshow(imagem_modelo, cmap="gray")
    plt.title(f"Exemplo MNIST da classe {predicao}")
    plt.axis("off")

plt.tight_layout()
plt.show()